### ISSUE TITLE
Lisk HUB 1.1.0 MacOS "Account Following" feature doesn't update balances of accounts you follow until you restart it.

### ISSUE THREAD

**Issue by blockcoinAU** [LiskHQ/lisk-hub#1239] opened 2018-09-03 05:31 UTC
Lisk Hub 1.1.0 MacOS 

### Expected behaviour
Balances of accounts you follow should update automatically. The LSK price chart should update dynamically as time goes by. 

### Actual behaviour
Balances of accounts you follow do not get updated. When clicking on the account to see the details, the latest transactions will show up but the total balance in the overview will remain stuck on the old information until you restart Lisk Hub. 

The same goes for the LSK price chart shown in the Dashboard.

### Steps to reproduce
Check the balance shown in the "Following" section, then click on the account to show the details. The latest transactions will be displayed and the total LSK held in the account will show the correct number. When you go back to the overview, the total will remain stuck showing an old balance from when you started LISK HUB. Only a restart seems to properly update the balances. The price chart DOES get updated if you come back to the dashboard but remains static while you're staying there.

**Comment by slaweet** [comment] 2018-09-27 10:29
Closing as duplicate to https://github.com/LiskHQ/lisk-hub/issues/1188 The issue is still open.

**Closed by slaweet** 2018-09-27 10:29 UTC
Labels: duplicate
