### ISSUE TITLE
Hub version check download and install fail

### ISSUE THREAD

**Issue by Phoenix1969** [LiskHQ/lisk-hub#700] opened 2018-04-06 16:40 UTC
### Expected behaviour 
download rc2 and install
![avail](https://user-images.githubusercontent.com/18568844/38433065-3f547708-3965-11e8-865e-0c8c50116fd5.PNG)

### Actual behaviour 
downloads and throws error
![rc4](https://user-images.githubusercontent.com/18568844/38433049-34b21a26-3965-11e8-91ed-2428726d621b.PNG)

### Steps to reproduce 
start hub and click "update now" on new rc

**Comment by Joo5t** [comment] 2018-06-01 14:26
I had the same, but the error appeard to me when I pressed the update button for the second time as I was getting impatient and had no download/update indicator.

**Comment by slaweet** [comment] 2018-06-04 06:17
@Joo5t thanks for the report.
The error reported by @Phoenix1969 in 0.4.0-rc.2 was caused by a failure in the build process that occurred only in this one version any subsequent releases should be free of this particular error.

What version was it in your case? There was a similar error that will be fixed in 0.8.0, planned for this Wednesday. Can it be this one https://github.com/LiskHQ/lisk-hub/issues/808?

**Comment by Joo5t** [comment] 2018-06-04 12:20
Im not exactly sure but I think its best to close this up and if it happens again I will report it.

**Comment by slaweet** [comment] 2018-06-04 12:28
Ok. Thanks @Joo5t

**Closed by slaweet** 2018-06-04 12:28 UTC
